# This file was generated by liblab | https://liblab.com/

from test_sdk import TestSdk, Environment

sdk = TestSdk(access_token="YOUR_ACCESS_TOKEN", base_url=Environment.DEFAULT.value)

result = sdk.pets.list_pets(limit=30)

print(result)
