name: Update github
on:
  push:
    branches:
      - main
jobs:
  trigger-other-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Update static asset for sdk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_REPO: "hub"
          TARGET_OWNER: "liblaber"
          TARGET_WORKFLOW: "update-static-assets.yaml"
          TARGET_BRANCH: "main"
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/$TARGET_OWNER/$TARGET_REPO/actions/workflows/$TARGET_WORKFLOW/dispatches \
          -d '{"ref":"topic-branch","inputs":{"name":"Mona the Octocat","home":"San Francisco, CA"}}'
