name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Update up main branch
        run: liblaber/hub/.github/workflows/update-static-assets.yaml@main
