name: Update github

on:
  push:
    branches:
      - main

jobs:
  trigger-other-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Update static asset for sdk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_REPO: "liblaber/hub"
          TARGET_WORKFLOW: "update-static-assets.yml"
          TARGET_BRANCH: "main"
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            https://api.github.com/repos/$TARGET_REPO/actions/workflows/$TARGET_WORKFLOW/dispatches \
            -d '{"ref":"$TARGET_BRANCH"}'

  # uses: liblaber/hub/.github/workflows/update-static-assets.yaml@main
